name: Lint and Test

on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: pnpm/action-setup@v4
      with:
        version: 9.6.0

    - name: Install Dependencies
      run: pnpm ci

    - name: Run Lint
      run: pnpm run lint

    - name: Run Test
      run: pnpm run test


